export const cartActionsType = {
    TOOGLE_CART_HIDDEN: 'TOOGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    CHECK_OUT_CART: 'CHECK_OUT_CART',
    SET_USER_CART_ITEMS: 'SET_USER_CART_ITEMS',
    UPDATE_USER_CART_ITEMS : 'UPDATE_USER_CART_ITEMS',
    CLEAN_USER_CART_ITEMS: 'CLEAN_USER_CART_ITEMS'
}